export const SET_TRABALHADOR_LISTA = 'TRABALHADOR_LISTA';
export const SET_TRABALHADOR_EDITAR = 'TRABALHADOR_EDITAR';
export const SET_TRABALHADOR_MSG = 'TRABALHADOR_MSG';
export const SET_TRABALHADOR_NOTIFICACAO = 'TRABALHADOR_NOTIFICACAO';
export const SET_TRABALHADOR_QUANTNOTIFICACAO = 'TRABALHADOR_QUANTNOTIFICACAO';